changed lint issues
chase-moskal/xiome pull request #127
Opened 2022-01-29 09:31 UTC by Tuasegun

2022-01-29 09:32 UTC, Tuasegun commented
@chase-moskal this is nstyles it's also coming up with conflicts but I've corrected the tab issues

2022-01-30 03:23 UTC, chase-moskal requested changes
- the package lock is broken. we should omit any changes to package-lock.json in this pr.
- the indentation and formatting is still quite wonky, we really want consistent indentation and formatting throughout the project.

2022-01-30 03:23 UTC, chase-moskal commented on s/features/notes/components/notes/xiome-notes.css.ts
> +	}
this excess indent on the closing brace doesn't look right

2022-01-30 03:23 UTC, chase-moskal commented on s/features/notes/components/notes/xiome-notes.css.ts
> +import { css } from "../../../../framework/component.js";
- the formatting here doesn't match the rest of the project

2022-01-30 03:23 UTC, chase-moskal commented on s/features/notes/components/notes/xiome-notes.css.ts
> +}
this style appears unused, and should probably be removed

2022-01-30 03:23 UTC, chase-moskal commented on s/features/notes/components/notes/xiome-notes.css.ts
> +	flex: 7;
i'm suspicious of this rule: why `flex: 7`, specifically?

2022-01-30 03:23 UTC, chase-moskal commented on s/features/notes/components/notes/xiome-notes.css.ts
> +	padding: 10px 10px 10px 10px;
in modern css, we want to avoid using `px` units, preferring instead to use flexible `em` units wherever possible

2022-01-30 03:23 UTC, chase-moskal commented on s/features/notes/components/notes/xiome-notes.css.ts
> +`;
no semicolons please :)

2022-01-30 03:23 UTC, chase-moskal commented on s/features/notes/components/notes/xiome-notes.ts
> +import { renderOp }	from "../../../../framework/op-rendering/render-op.js"
the formatting on these imports don't quite match the rest of the project

2022-01-30 03:23 UTC, chase-moskal commented on s/features/notes/components/notes/xiome-notes.ts
> +	notesModel: ReturnType<typeof makeNotesModel>
something's wrong with the indentation here

2022-01-30 03:23 UTC, chase-moskal commented on s/features/notes/components/notes/xiome-notes.ts
> +		async init() {
excess indent

2022-01-30 03:23 UTC, chase-moskal commented on s/features/notes/components/notes/xiome-notes.ts
> +	]
there is a hidden spacebar after the `]` character, we want to avoid trailing whitespace

2022-01-30 03:23 UTC, chase-moskal commented on s/features/notes/components/notes/xiome-notes.ts
> +			this.#cache.fetchAppropriateNotes()
more trailing whitespace

2022-01-30 03:23 UTC, chase-moskal commented on s/features/notes/components/notes/xiome-notes.ts
> +	return () => unsubs.forEach((unsub) => unsub())
more trailing whitespace

2022-01-30 03:23 UTC, chase-moskal commented on s/features/notes/components/notes/xiome-notes.ts
> +			const { old } = this.#cache.cacheState
we prefer to avoid the spaces between `{` and `}`

2022-01-30 03:23 UTC, chase-moskal commented on s/features/notes/components/notes/xiome-notes.ts
> +					<div class="tabs">
the indentation in this area isn't quite right

2022-01-30 03:23 UTC, chase-moskal commented on s/features/notes/components/notes/xiome-notes.ts
> +			const { old, notesOp } = this.#cache.cacheState
excess indentation here

2022-01-30 03:23 UTC, chase-moskal commented on s/features/notes/components/notes/xiome-notes.ts
> +							${notes.map((note) => html`
excess indentation

2022-01-30 03:23 UTC, chase-moskal commented on s/features/notes/components/notes/xiome-notes.ts
> +			const { pageNumber } = this.#cache.cacheState
excess indentation

2022-01-30 03:23 UTC, chase-moskal commented on s/features/notes/components/notes/xiome-notes.ts
> +			const { old } = this.#cache.cacheState
indentation

2022-01-30 03:23 UTC, chase-moskal commented on s/features/notes/components/notes/xiome-notes.ts
> +				const { old, notesOp } = this.#cache.cacheState
indentation

2022-01-30 03:23 UTC, chase-moskal commented on s/features/notes/components/notes/xiome-notes.ts
> +							? html`
indentation

2022-02-06 03:36 UTC, chase-moskal commented
closing in favor of #130

2022-02-06 03:36 UTC, closed without merging